"""Added relationships to User model for created and assigned issues

Revision ID: 535016d5ae70
Revises: 91185e2ee860
Create Date: 2026-01-11 16:07:40.618752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535016d5ae70'
down_revision: Union[str, Sequence[str], None] = '91185e2ee860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
