"""add user role

Revision ID: af721f2cc8bb
Revises: 8547fe31aad3
Create Date: 2026-01-22 13:35:18.541675

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af721f2cc8bb"
down_revision: Union[str, Sequence[str], None] = "8547fe31aad3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Enum Creation for Postgres
    userrole = sa.Enum("ADMIN", "TEAM_LEAD", "MEMBER", name="userrole")
    userrole.create(op.get_bind())

    # Added server_default='MEMBER' to handle existing rows
    op.add_column(
        "users", sa.Column("role", userrole, nullable=False, server_default="MEMBER")
    )
    op.add_column("users", sa.Column("team_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "users", "teams", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "team_id")
    op.drop_column("users", "role")

    # Manual Enum Drop for Postgres
    userrole = sa.Enum("ADMIN", "TEAM_LEAD", "MEMBER", name="userrole")
    userrole.drop(op.get_bind())
    # ### end Alembic commands ###
