"""Make activity old_value nullable

Revision ID: d99abee30e4e
Revises: 6f968222acbb
Create Date: 2026-02-03 16:46:26.889210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99abee30e4e'
down_revision: Union[str, Sequence[str], None] = '6f968222acbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'old_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'old_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
